### ISSUE TITLE
Travis Gentoo Tree

### ISSUE THREAD

**Issue by theCoolkal** [RiceBowlLinux/ricebowl-overlay#2]
We're using the Gentoo Portage tree now as a base.  Could we change it back to Gentoo in Travis?

Also, is there any way of making Travis use Paludis instead of Portage?  Or is that not needed?

**Comment by urras** [comment]
>Also, is there any way of making Travis use Paludis instead of Portage? Or is that not needed?
I haven't worked with Paludis before, so if you can get it working, I'll review and merge
